/* Copyright (c) 2002-2013 Pigeonhole authors, see the included COPYING file
 */

#ifndef __EXT_EDITHEADER_LIMITS_H
#define __EXT_EDITHEADER_LIMITS_H

#define EXT_EDITHEADER_MINIMUM_MAX_HEADER_SIZE  1024
#define EXT_EDITHEADER_DEFAULT_MAX_HEADER_SIZE  2048

#endif /* __EXT_EDITHEADER_LIMITS_H */
