#!/bin/sh

## serial 1

if test "${VERSION}" != ""; then
  VN=`echo ${VERSION} | sed -e "s/^\([0-9]*\.[0-9]*\)\.\([0-9]*\).*/dovecot-\1-pigeonhole/"`
elif test -f version; then
  VN=`cat version`
  VN=`echo $VN | sed -e "s/^\([0-9]*\.[0-9]*\)\.\([0-9]*\).*/dovecot-\1-pigeonhole/"`
else
  VN='dovecot-0.0-pigeonhole'
fi

echo $VN
